### ISSUE TITLE
US 1 - Starting Page with Navigation 

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#1]
## Value Proposition

**As a** ... User
**I want to** ... get an overview and see how to navigate through the app in the first place 
**so that** ... I know how to use it.
​

## Description
<img width="247" alt="Bildschirm­foto 2023-03-03 um 12 38 15" src="https://user-images.githubusercontent.com/104009848/222711139-e9d3dfca-da94-49c9-85eb-e99ee8d11dcd.png">

## Acceptance Criteria

- [ ] The buttons should navigate to different pages by click / tap 
- [ ] The "+" Add Button should link to survey
      ​

## Tasks

- [ ] Create a reusable button component "NavItems"
- [ ] Create a "+" ADD Button to start new survey by "onClick"
- [ ] Create a reusable nav-component with two buttons as Nav-Items 
- [ ] Add onClick event on each button 
- [ ] Route pages in Next.js
      ​

## Complexity

- [ ] M

**Comment by MelissaDuve** [comment]
this is a very nice user story 👌

**Comment by SarahWett** [comment]
Thank you very much for your review @MelissaDuve

**Comment by MartinK1983** [comment]
thats nice
