### ISSUE TITLE
US 7 - All Entries 

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#11]
## Value Proposition

**As a** ... User tracking my mood, habit and additional. info
**I want to** ... access the infos displayed as separate cards 
**so that** ... I can see the data of every entry
​

## Description
<img width="220" alt="Bildschirm­foto 2023-03-10 um 10 27 23" src="https://user-images.githubusercontent.com/104009848/224277980-1429c649-425d-44f9-be6a-e3dc23800395.png">

​

## Acceptance Criteria

- [ ] by selecting Card "All Entries" you should see a list of all entries displayed as card components
- [ ] the entries should include data of all three questions
- [ ] as card header there should be displayed the date of the entry 
      ​

## Tasks

- [ ] link to all entries page
- [ ] create reusable card component 
- [ ] install uid to display unique entries 
- [ ] grab formData to display it 
- [ ] create header, body and two div's to display data of single form questions seperately
- [ ] get Date to be displayed as Card Header 

## Comment
- [ ] The Edit / Delete Function are already wireframed here - but will be part of the next US - not this one 
      ​

## Complexity

L

**Comment by TuncAlt** [comment]
Looks good!
