### ISSUE TITLE
US 8 - Edit Function

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#12]
## Value Proposition

**As a** ... User tracking my Mood 
**I want to** ... have the possibility to edit my entries
**so that** ... I can resolve mistakes.  
​

## Description
<img width="220" alt="Bildschirm­foto 2023-03-10 um 10 27 23" src="https://user-images.githubusercontent.com/104009848/224279875-a704e47d-8124-4573-92c3-62b4a74dc9d9.png">

​

## Acceptance Criteria

- [ ] Every single Entry should have a editing Button
- [ ] When clicking the Button you should be redirected to the Edit-Form
- [ ] The input fields to manage your inputs are displayed on one page
      ​

## Tasks

- [ ] create reusable Edit Button Component 
- [ ] redirect to input fields using dynamic next routing to [id].js
      
## Comment
- [ ] The updating data process is part of the next US but not this one here :) ​

## Complexity

L

**Comment by TuncAlt** [comment]
Looks good!
