### ISSUE TITLE
US 9 - Delete Function all Entries

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#13]
## Value Proposition

**As a** ... user tracking my mood
**I want to** ... be able to delete entries
**so that** ... to manage my data.
​

## Description
<img width="220" alt="Bildschirm­foto 2023-03-10 um 10 27 23" src="https://user-images.githubusercontent.com/104009848/224280749-6cc15cb1-2936-4bbf-bddf-090964efeb3c.png">

​

## Acceptance Criteria

- [ ] A Delete Button should be displayed on every card component
- [ ] when clicking the delete button there should be popup to confirm deletion 
- [ ] when clicking confirm the entry data should be deleted / not visible anymore
      ​

## Tasks

- [ ] Create reusable Delete Button Component
- [ ] Write delete function 
- [ ] Create popUp for confirmation
- [ ] remove entry from formData / all Entries Page 

## Complexity

XL

**Comment by TuncAlt** [comment]
Looks good!
