### ISSUE TITLE
US 10 : EditForm displays current data 

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#19]
## Value Proposition

**As a** ... User who wants to edit former entries
**I want to** ... see what I've chosen in the first place
**so that** ... so I can see what didn't meet my actual thoughts for this day.
​

## Description
<img width="361" alt="Bildschirm­foto 2023-03-22 um 23 14 50" src="https://user-images.githubusercontent.com/104009848/227050587-ec17b537-56b3-4227-8f97-7aed308bc3ae.png">

## Acceptance Criteria

- [ ] When the edit page opens I want to see which options I previously have chosen in the first place 
- [ ] I want to be able edit all 3 input fields and see which is checked now
      ​

## Tasks

- [ ] create localStorageState to the EditForm
      ​

## Complexity

S

**Comment by Marcel-FR** [comment]
LGTM!
