### ISSUE TITLE
US 2 - Survey Page - First Question 

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#2]
## Value Proposition
As an interested in Mental-Health 
I want to track my moody behavior in a daily basis, 
so that I can get an overview about my feelings.

## Description
<img width="232" alt="Bildschirm­foto 2023-03-03 um 12 58 04" src="https://user-images.githubusercontent.com/104009848/222727179-117ec147-7642-41dd-a907-6614d86098b9.png">

## Acceptance criteria
- [ ] The question is displayed with 4 smileys as answer options (single choice)  
- [ ] By confirming "next"-Button - it's skipped to the next page / question

## Tasks
- [ ] Create a reusable Single Choice Component with the RadioButtons replaced by Smiley SVG / Omg 
- [ ] Create a stepper & Route pages with Next.js
- [ ] Save the value range of the smileys clicked to 
 later on be presented in the dashboard modules [ Local State !! ]
      ​

## Complexity

- [ ] L

**Comment by pung-one** [comment]
looks good! in the "complexity" category it's enough to just write a "size-letter" from XS - XL i think :)
