### ISSUE TITLE
US 12 : BarChart

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#21]
## Value Proposition

**As a** ... user tracking my data
**I want to** ... see an overview of how often my mood was good / bad
**so that** ... I can reflect myself.  
​

## Description
<img width="319" alt="Bildschirm­foto 2023-03-23 um 08 06 34" src="https://user-images.githubusercontent.com/104009848/227152058-be85640a-9c5f-4393-9ac3-fbc46fe59059.png">

​

## Acceptance Criteria

- [ ] There should be an Bar-Chart with Header "Mood-Bar" 
- [ ] chart displays how often a specific mood was clicked yet 
      ​

## Tasks

- [ ] implement charts.js 
- [ ] import Bar-Chart 
- [ ] access formData in the Bar-Chart module 
- [ ] create different colors for the different values 
- [ ] import Header & Navbar with Navigation-Items 
      ​

## Complexity

L
