### ISSUE TITLE
US 13: Timeline Chart

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#22]
## Value Proposition

**As a** ... user tracking my data 
**I want to** ... see the progress of my mood so far
**so that** ... I can deduce tendencies. 
​

## Description
<img width="309" alt="Bildschirm­foto 2023-03-23 um 08 06 42" src="https://user-images.githubusercontent.com/104009848/227153549-4fbb8b1c-e0ff-4266-810e-7f19645f1648.png">

​

## Acceptance Criteria

- [ ] Timeline which represents the mood entries until now 
- [ ] x = time 
- [ ] y = mood 
- [ ] navigation menue to navigate away from this page 
- [ ] header to get information where I am at the moment 
      ​

## Tasks

- [ ] import charts.js timeline 
- [ ] import header & Navbar with Nav-Items 
- [ ] access formData inside of the charts.js module
- [ ] define time shown 
      ​

## Complexity

XL
