### ISSUE TITLE
US 15 : Filter Function

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#29]
## Value Proposition

**As a** ... User tracking my mood
**I want to** ...filter the entries by habits
**so that** ... I can detect what triggers my mood.
​

## Description
<img width="258" alt="Bildschirm­foto 2023-03-27 um 13 57 06" src="https://user-images.githubusercontent.com/104009848/228050429-f083507c-b79a-49f8-ac93-beb48e59dc9a.png">

​

## Acceptance Criteria

- [ ] Visible DropDown Menu with several tags options 
- [ ] When clicking a tag, only those entries containing it appear in the list
- [ ] Also the "All Entries: X" - Batch will only count the amount of entries displayed currently 
      ​

## Tasks

- [ ] Create Dropdown 
- [ ] filter tags 
- [ ] state for the entries 
      ​

## Complexity

M
