### ISSUE TITLE
US 3 - Q2 Textarea

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#3]
As a User tracking my mood 
there might be something special from time to time,
so I wanna get the possibility to add some notes if necessary.  

## Description
<img width="248" alt="Bildschirm­foto 2023-03-03 um 14 25 19" src="https://user-images.githubusercontent.com/104009848/222731590-a0146488-0a10-4050-952d-eedde4df49cf.png">

## Acceptance criteria
- [ ] There has to appear a "confirm"-button on the bottom of the page
- [ ] It's feasible to write some text inside an text area

## Tasks
- [ ] Create Textarea which isn't required to be filled out
- [ ] Create a Button on the bottom of the page 
- [ ] Create "handleSubmit function" to route to next page & save the data 
      ​
## Complexity
- [ ] S/M

**Comment by Marcel-FR** [comment]
LGTM !
