### ISSUE TITLE
US 16: Loading Page 

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#30]
## Value Proposition

**As a** ... User interacting with an App
**I want to** ... see a loading screen instead of nothing happening at all 
**so that** ... I do have a visual feedback knowing it's processing.
​

## Description
<img width="260" alt="Bildschirm­foto 2023-03-28 um 10 17 29" src="https://user-images.githubusercontent.com/104009848/228174861-d991d4f7-9150-4487-ba31-52c70f731327.png">

​

## Acceptance Criteria

- [ ] If a redirection takes some seconds there will be a Loading page displayed to give the user visual feedback 
- [ ] the Loading-Screen contains a Header "Let us move .." 
- [ ] the Loading-Screen contains an animation 
      ​

## Tasks

- [ ] create loading  State in app.js 
- [ ] define start / end according to specific router events 
- [ ] create a PageLoader component
      ​

## Complexity

S
