### ISSUE TITLE
Finalizing Styles

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#33]
## Value Proposition

**As a** ... User
**I want to** ... be confronted with an appealing but yet consistent style
**so that** ... I can overlook functions and capabilities.
​

​

## Acceptance Criteria

- [ ] Consistent style system 
- [ ] visual appealing effects to know when e.g content is loading 
- [ ] clickable content can be determined as such 
- [ ] color palette is consistent 
- [ ] soothing page transitions
      ​

## Tasks

- [ ] create different states 
- [ ] refactor styles code to be stored in separate style files 
- [ ] check color palette & design system 
      ​

## Complexity

S
