### ISSUE TITLE
US: Accessibility

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#38]
## Value Proposition

**As a** ... User interacting with an App
**I want to** ... be able to use a screenreader without having comprehension issues 
**so that** ... I can use the App properly with visual impairment, too. 
​

## Acceptance Criteria

- [ ] Screen Reader should get aria-labels to give informationto the user properly
      ​

## Tasks

- [ ] Create aria-labels to interactive content such as buttons
- [ ] Create aria-labeledBy to non-interactive elements
      ​

## Complexity

S
