### ISSUE TITLE
US 5 - Final survey page

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#4]
As a User after confirming the survey, 
I want to get some Feedback 
so I can be sure everything worked out properly

## Description
<img width="307" alt="Bildschirm­foto 2023-03-03 um 14 55 19" src="https://user-images.githubusercontent.com/104009848/222738824-7198242e-49af-461e-9fbd-858de8ef4377.png">

## Acceptance criteria
- [ ] no buttons but automatically redirection to starting screen
- [ ] The page content isn't clickable anymore
- [ ] page visible for about 3 seconds

## Tasks
- [ ] Create h1 with the text "SAVED!" 
- [ ] Create redirection
- [ ] Adapt handle submit

## Complexity
- [ ] M

**Comment by christopher-koch** [comment]
LGTM!
