### ISSUE TITLE
US: Refactoring

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#40]
## Value Proposition

**As a** ... development colleague 
**I want to** ... read refactored & organized code
**so that** ... I can understand tasks easily and don't have to waste time.

​

## Acceptance Criteria

- [ ] code is clean
- [ ] styles in separate files inside the folder of the component as necessary 
- [ ] "don't repeat yourself" - rather uplift code e.g. into app.js than repeat it several times if possible 
- [ ] naming of variables & functions are clear & reasonable 
      ​

## Tasks

- [ ] re-check spelling & reasonable naming 
- [ ] re-check Next.js naming conventions
- [ ] uplift the "listOfOptions" as "listOfSmileyOptions" and "listOfTagOptions" in app.js & handle down as props
      ​

## Complexity

M
