### ISSUE TITLE
US 6 - Dashboard Overview Page

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#5]
## Value Proposition

As someone tracking his daily mood & habits, 
I want to get an overview via Dashboard, too 
so I can decide what data I wanna see.

## Description
<img width="282" alt="Bildschirm­foto 2023-03-03 um 15 15 03" src="https://user-images.githubusercontent.com/104009848/222743621-9b162063-b4d8-4172-9b00-6e7e83f787c0.png">

## Acceptance criteria
- [ ] need a Dashboard-Overview site with 3 larger cards including the buzzwords
- [ ] Buzzwords have to be clear & comprehensible 
- [ ] Each Card gives me a visual Feedback for me to notice it's clickable content

## Tasks
- [ ] Create large Card Component to be reused within this page 3 times
- [ ] Reuse NavBar Component from Homepage

## Comment
- [ ] There will be NO BACK BUTTON here because it's non-sense on this point you can click the home button
- [ ] Back-Button will be visible within the next two US :) 

## Complexity
- [ ] S

**Comment by B-Homsi** [comment]
Time for a Happy Mood!!
