### ISSUE TITLE
US 3 - Question with tags/ MS

### ISSUE THREAD

**Issue by SarahWett** [SarahWett/capstone-project#6]
## Value Proposition

As someone tracking his daily mood, 
I want to track my habits, too 
so I can get more details.

## Description

<img width="228" alt="Bildschirm­foto 2023-03-03 um 16 46 10" src="https://user-images.githubusercontent.com/104009848/222764240-ca85128f-ec4b-4db1-b218-02e61adc6ed3.png">

## Acceptance criteria
- [ ] There has to appear a "confirm"-button on the bottom of the page
- [ ] It's feasible to select multiple tags / habits

## Tasks
- [ ] Create Multiple Choice question with multiple tags to select
- [ ] Create a Button on the bottom of the page 
- [ ]Add onClick event to get to the new page

## Complexity
M

**Comment by B-Homsi** [comment]
I like the simplicity of the UI !
